project_name: bubbly
builds:
  - id: bubbly
    binary: bubbly
    main: main.go
    flags:
      # include the ui in the build
      - -tags=ui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
      - amd64
    ignore:
      # some packages (e.g. zerolog, sqlite) don't have this combo
      - goos: windows
        goarch: arm64
    goarm:
      - 7

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: nix
    builds: [bubbly]

brews:
  - name: bubbly
    tap:
      owner: valocode
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://bubbly.dev/"
    description: "Bubbly"
    test: |
      system "#{bin}/bubbly --version"

dockers:
  - goos: linux
    goarch: amd64
    skip_push: false
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "valocode/{{ .ProjectName }}:latest"
      - "valocode/{{ .ProjectName }}:{{ .Tag }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: valocode
    name: bubbly
  prerelease: auto
  disable: false
  draft: false
