project_name: bubbly
before:
  hooks:
    - go get -u github.com/swaggo/swag/cmd/swag
builds:
  - binary: bubbly
    main: main.go
    env:
      - CGO_ENABLED=0
    hooks:
      pre: swag init
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 7
  - id: darwin
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
  - id: windows
    goos:
      - windows
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: nix
    builds: [linux, darwin]
    format: tar.gz
    files:
      - none*
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: windows
    builds: [windows]
    format: zip
    files:
      - none*
brews:
  - name: bubbly
    tap:
      owner: valocode
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://bubbly.dev/"
    description: "Bubbly CLI"
    test: |
      system "#{bin}/bubbly --version"
dockers:
  - goos: linux
    goarch: amd64
    skip_push: false
    use_buildx: true
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "valocode/{{ .ProjectName }}:latest"
      - "valocode/{{ .ProjectName }}:{{ .Tag }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: valocode
    name: bubbly
  prerelease: auto
  disable: false
  draft: false
