project_name: bubbly
builds:
  - id: bubbly
    binary: bubbly
    main: main.go
    env:
      - CGO_ENABLED=0
    flags:
      # include the ui in the build
      - -tags=ui
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
archives:
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: nix
    builds: [linux, darwin]
    format: tar.gz
    files:
      - none*
  - name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    id: windows
    builds: [windows]
    format: zip
    files:
      - none*
brews:
  - name: bubbly
    tap:
      owner: valocode
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: "https://bubbly.dev/"
    description: "Bubbly"
    test: |
      system "#{bin}/bubbly --version"
dockers:
  - goos: linux
    goarch: amd64
    skip_push: false
    use: buildx
    dockerfile: Dockerfile.goreleaser
    image_templates:
      - "valocode/{{ .ProjectName }}:latest"
      - "valocode/{{ .ProjectName }}:{{ .Tag }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
      - "valocode/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
      - "--pull"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: valocode
    name: bubbly
  prerelease: auto
  disable: false
  draft: false
