version: "3.9"

volumes:
  postgres-data:

services:
  # Bubbly agent
  bubbly:
    depends_on:
      - "${BUBBLY_STORE_PROVIDER:-postgres}"
    container_name: bubbly
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BUBBLY_STORE_PROVIDER: "${BUBBLY_STORE_PROVIDER:-postgres}"
      BUBBLY_AUTHENTICATION: "${BUBBLY_AUTHENTICATION:-false}"
      BUBBLY_MULTITENANCY: "${BUBBLY_MULTITENANCY:-false}"
      BUBBLY_AUTH_API: "http://bubbly-auth:1323/api/v1"
    networks:
      - bubbly-net
    ports:
      - "8111:8111" # bubbly agent
      - "8222:8222" # NATS HTTP
      - "4223:4223" # NATS service
    command:
      - "server"
      - "--debug"


      # One of the Store options for Bubbly
  postgres:
    image: postgres:13.0
    container_name: postgres
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-postgres}"
      POSTGRES_DB: "${POSTGRES_DATABASE:-bubbly}"
    networks:
      - bubbly-net
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data

# User-defined bridge network is different from the default bridge
networks:
  bubbly-net:
    driver: bridge
    internal: false
