// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/valocode/bubbly/ent/cvescan"
	"github.com/valocode/bubbly/ent/release"
	"github.com/valocode/bubbly/ent/releaseentry"
	"github.com/valocode/bubbly/ent/vulnerability"
)

// CVEScanCreate is the builder for creating a CVEScan entity.
type CVEScanCreate struct {
	config
	mutation *CVEScanMutation
	hooks    []Hook
}

// SetTool sets the "tool" field.
func (csc *CVEScanCreate) SetTool(s string) *CVEScanCreate {
	csc.mutation.SetTool(s)
	return csc
}

// SetReleaseID sets the "release" edge to the Release entity by ID.
func (csc *CVEScanCreate) SetReleaseID(id int) *CVEScanCreate {
	csc.mutation.SetReleaseID(id)
	return csc
}

// SetRelease sets the "release" edge to the Release entity.
func (csc *CVEScanCreate) SetRelease(r *Release) *CVEScanCreate {
	return csc.SetReleaseID(r.ID)
}

// SetEntryID sets the "entry" edge to the ReleaseEntry entity by ID.
func (csc *CVEScanCreate) SetEntryID(id int) *CVEScanCreate {
	csc.mutation.SetEntryID(id)
	return csc
}

// SetNillableEntryID sets the "entry" edge to the ReleaseEntry entity by ID if the given value is not nil.
func (csc *CVEScanCreate) SetNillableEntryID(id *int) *CVEScanCreate {
	if id != nil {
		csc = csc.SetEntryID(*id)
	}
	return csc
}

// SetEntry sets the "entry" edge to the ReleaseEntry entity.
func (csc *CVEScanCreate) SetEntry(r *ReleaseEntry) *CVEScanCreate {
	return csc.SetEntryID(r.ID)
}

// AddVulnerabilityIDs adds the "vulnerabilities" edge to the Vulnerability entity by IDs.
func (csc *CVEScanCreate) AddVulnerabilityIDs(ids ...int) *CVEScanCreate {
	csc.mutation.AddVulnerabilityIDs(ids...)
	return csc
}

// AddVulnerabilities adds the "vulnerabilities" edges to the Vulnerability entity.
func (csc *CVEScanCreate) AddVulnerabilities(v ...*Vulnerability) *CVEScanCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return csc.AddVulnerabilityIDs(ids...)
}

// Mutation returns the CVEScanMutation object of the builder.
func (csc *CVEScanCreate) Mutation() *CVEScanMutation {
	return csc.mutation
}

// Save creates the CVEScan in the database.
func (csc *CVEScanCreate) Save(ctx context.Context) (*CVEScan, error) {
	var (
		err  error
		node *CVEScan
	)
	if len(csc.hooks) == 0 {
		if err = csc.check(); err != nil {
			return nil, err
		}
		node, err = csc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CVEScanMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = csc.check(); err != nil {
				return nil, err
			}
			csc.mutation = mutation
			if node, err = csc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(csc.hooks) - 1; i >= 0; i-- {
			mut = csc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (csc *CVEScanCreate) SaveX(ctx context.Context) *CVEScan {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// check runs all checks and user-defined validators on the builder.
func (csc *CVEScanCreate) check() error {
	if _, ok := csc.mutation.Tool(); !ok {
		return &ValidationError{Name: "tool", err: errors.New("ent: missing required field \"tool\"")}
	}
	if v, ok := csc.mutation.Tool(); ok {
		if err := cvescan.ToolValidator(v); err != nil {
			return &ValidationError{Name: "tool", err: fmt.Errorf("ent: validator failed for field \"tool\": %w", err)}
		}
	}
	if _, ok := csc.mutation.ReleaseID(); !ok {
		return &ValidationError{Name: "release", err: errors.New("ent: missing required edge \"release\"")}
	}
	return nil
}

func (csc *CVEScanCreate) sqlSave(ctx context.Context) (*CVEScan, error) {
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (csc *CVEScanCreate) createSpec() (*CVEScan, *sqlgraph.CreateSpec) {
	var (
		_node = &CVEScan{config: csc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: cvescan.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cvescan.FieldID,
			},
		}
	)
	if value, ok := csc.mutation.Tool(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: cvescan.FieldTool,
		})
		_node.Tool = value
	}
	if nodes := csc.mutation.ReleaseIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cvescan.ReleaseTable,
			Columns: []string{cvescan.ReleaseColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: release.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.cve_scan_release = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := csc.mutation.EntryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   cvescan.EntryTable,
			Columns: []string{cvescan.EntryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: releaseentry.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.release_entry_cve_scan = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := csc.mutation.VulnerabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   cvescan.VulnerabilitiesTable,
			Columns: []string{cvescan.VulnerabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: vulnerability.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CVEScanCreateBulk is the builder for creating many CVEScan entities in bulk.
type CVEScanCreateBulk struct {
	config
	builders []*CVEScanCreate
}

// Save creates the CVEScan entities in the database.
func (cscb *CVEScanCreateBulk) Save(ctx context.Context) ([]*CVEScan, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*CVEScan, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CVEScanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *CVEScanCreateBulk) SaveX(ctx context.Context) []*CVEScan {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
