## workflow for running the build and unit tests

on:
  # run this workflow on any branch or a PR
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

name: simple
jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: ./ui
      - run: npm run build --if-present
        working-directory: ./ui
  backend:
    strategy:
      # matrix lets us expand our range of OSs / go
      matrix:
        go-version: [1.17]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        # Skip install if testing action locally using act
        if: ${{ !env.ACT }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: cache go mod
        # Skip caching if testing action locally using act
        if: ${{ !env.ACT }}
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test
        run: go test -failfast ./...
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot
